markdown: pandoc
#pygments: true
permalink: "/:title"
#rdiscount:
#  extensions: [smart]

name: evanlivingston
name_part: vanlivingston
initial: e
url: http://evanlivingston.net
github: evanlivingston


post:
  template: _post.txt
  extension: md
  permalink: /thoughts/:title
page:
  template: _page.txt
  extension: md
editor: muo
git:
  branch: master

pandoc:
  format: html
  extensions:
    - bibliography: '_bibliography/references.bib'
    - smart
